config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end

  namespace :admin do
      resources :users
      resources :posts
      resources :admin_users
      resources :employee_users
      root to: "users#index"
    end

  resources :posts do
    member do 
      get :approve
    end
  end
  devise_for :users, skip: [:registration]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
    <%= js add_gritter(flash[:alert], :title => "alert notification", :sticky => false, time: 2000) %>
<% elsif flash[:error] %>
    <%= js add_gritter(flash[:error], :title => "error notification", :sticky => false, time: 2000) %>
<% else %>
    <%= js add_gritter(flash[:notice], :title => "notice notification", :sticky => false, time: 2000) %>
<% end %>

app/views/shared/_nav.html.erb
<% if current_user %>
    <ul class="nav nav-tabs mx-2">
    	<li class="nav-item <%=active?(root_path)%>">
            <%= link_to "Home", root_path %>
    	</li>
    	<li class="nav-item <%=active?(posts_path)%>">
            <%= link_to "All overtime", posts_path %>
        </li>
        <% if current_user.type == "AdminUser"%>
            <li class="nav-item <%=active?("/admin")%>">
                <%= link_to "Admin dashboard", admin_root_path %>
            </li>
            <li class="nav-item <%=active?("/admin")%>">
                <%= link_to "Audit log", audit_logs_path %>
            </li>
        <% end %>    
        <li class="nav-item <%=active?(new_post_path)%>">
            <%= link_to "Overtime request", new_post_path, id: "new_post_nav_link" %>
    	</li>
        <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    	</li>
    </ul>
<% end %>